### ISSUE TITLE
Local URLS not working

### ISSUE THREAD

**Issue by AlexHenkel** [wemersonjanuario/laravelpdf#1]
I'm working on my localhost trying to load a view as PDF. 

I've tried to do with `loadView()` method, parsing the view to a HTML string and using `loadHTML()` method, and also using the URL with `loadURL('http://localhost/')` and `loadURL('http://127.0.0.1/')`. But everytime I try any of these options, localhost crashes and I even have to restart it to work with it again. 

After debugging the HTML code, I found out that local links were causing that problem with this format: `http://localhost/files/2015/04/products/1428708073_554-large.jpg` and these happens with images and CSS files. 

Also if I try to load the part of my site that is already in production as `loadURL('http://jyrsa.scitus.mx/')` it gives me the next error: 
![screen shot 2015-04-20 at 7 37 01 pm](https://cloud.githubusercontent.com/assets/6724081/7243619/1463e602-e795-11e4-8d58-ee75635c0adf.png)
So there might be something wrong in the HTML.

Do you have any idea what is wrong? Thank's!

**Comment by wemersonjanuario** [comment]
Hi friend LoadURL method is working, maybe you have broken links inside your html src.
Check if http://localhost/files/2015/04/products/1428708073_554-large.jpg exists. Blade Views can't throw exceptions.
