### ISSUE TITLE
font-size && picture too small

### ISSUE THREAD

**Issue by dlouvard** [wemersonjanuario/laravelpdf#12]
Hi,

I must use zoom at 3 to see normally because by defaut, all my fonts and pictures are very very small. Have you a idea why?

Thanks

**Comment by dlouvard** [comment]
My configuration font : 
body {
            font-family:  Helvetica, Verdana, sans-serif;
            font-size: 15px;
        }

**Comment by dlouvard** [comment]
Example : [test.pdf](https://github.com/wemersonjanuario/laravelpdf/files/841502/test.pdf)

**Comment by wemersonjanuario** [comment]
Ohhh, I have never seen this before. try to update to 1.1.*. Try to create a fresh blade view to test it again. Let me know if it works. thank you

**Comment by dlouvard** [comment]
Thanks you for your answer, i will test it

**Comment by dlouvard** [comment]
same problem :-(

**Comment by dlouvard** [comment]
sorry

**Comment by wemersonjanuario** [comment]
What is your O.S? What wkhtmltopdf version are you using? how executable is configured?

**Comment by dlouvard** [comment]
OS: Mac OS 10.11.6 EL Capitan
wkhtmltopdf 0.12.4 (with patched qt)
executable (config/laravelpdf) : 'executable' => '/usr/local/bin/wkhtmltopdf'

**Comment by wemersonjanuario** [comment]
This seems to be the executable you are using. Have you tryied to use another wkhtmltopdf version?

**Comment by dlouvard** [comment]
OK, if i test with 0.12.3, the zoom is not necessary but now code 504. Maybe too information showing. and if retest 0.12.4, zoom at 2 with normal presentation. So, i think i will stay with this configuration

**Comment by dlouvard** [comment]
bizarre

**Comment by dlouvard** [comment]
thanks for your help

**Comment by wemersonjanuario** [comment]
haha, here we are!
