### ISSUE TITLE
Generate more then two PDF's

### ISSUE THREAD

**Issue by maisn3r** [wemersonjanuario/laravelpdf#2]
Problem is when i call the Method in controller twice generator making two files with exacly same content, tested with loadHtml and loadUrl,

```
public function savespo($id) {

    PDF::loadURL('http://belmont.beta.webintrix.com/admin/shipments/spo/'.$id)->pageSize('A2')->save("QFL Job 50 - Purchase Order to Supplier - Reference SPO.pdf", new Adapter( public_path() . '/uploads/shipments/'.$id.'/internal/'));

}

public function savecpfi($id) {

    PDF::loadURL('http://belmont.beta.webintrix.com/admin/shipments/cpfi/'.$id)->pageSize('A2')->save("QFL Job 50 - Belmont PFI to Customer - Reference CPFI.pdf", new Adapter( public_path() . '/uploads/shipments/'.$id.'/client/'));

}
```

This is my code, i get two PDF,s saved but content is from first instance.

**Comment by wemersonjanuario** [comment]
I think this is happening because you are using The PDF Facades with is singleton.
Try instantiante new PDF class for each diferent documents.

public function savespo($id)
    {
        $pdf = new \Inline\LaravelPDF\PDF(Config::get('laravelpdf.executable'));
        $pdf->loadURL('http://belmont.beta.webintrix.com/admin/shipments/spo/' . $id)
            ->pageSize('A2')
            ->save("QFL Job 50 - Purchase Order to Supplier - Reference SPO.pdf", new Adapter(public_path() . '/uploads/shipments/' . $id . '/internal/'));
    }

**Comment by maisn3r** [comment]
Thank you that works
