### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by NazarAli** [wemersonjanuario/laravelpdf#3]
thanks for u
i tray use it and this problem appear 
PDF could not be created: "The system cannot find the path specified.\r\n"

**Comment by wemersonjanuario** [comment]
Hi, did you publish config file? Did you set the correct wkhtmltopdf bin file in your laravelpdf.php config file? If Not, take a look at the suggest config in composer.json and and install
"wemersonjanuario/wkhtmltopdf-windows": "0.12.2.1", //FOR WINDOWS
    "h4cc/wkhtmltopdf-i386": "*" //FOR LINUX 32b
