### ISSUE TITLE
Creating a single pdf with multiple calls to loadview

### ISSUE THREAD

**Issue by corkysru** [wemersonjanuario/laravelpdf#5]
Is it possible to create a single pdf with multiple calls to loadview with different views and data being loaded into the view?

This is the situation:
One my project I currently have 5 different(and rather complicated) reports written. Each one is for a different medical test that could happen multiple times each day. Each one is generated with a unique view and unique array of data.
I am now trying to make a combination report for an entire day's worth of data. I was wondering if was possible to somehow just call the loadview multiple times to concat all the output of it into one pdf. 

Thanks

**Comment by dpovshed** [comment]
Hi @corkysru !

I had very similar case so I added functionality which might be interested for you.

You can either generate each report's HTML file and pass it to new loadHTMLs() function or just use loadViews() which accept an array of views.

Please note, loadViews() use the same $data array for all calls; if this does not fits your case - I believe you can easily extend the function in your own copy.

Hope this heps!

**Comment by dpovshed** [comment]
The patch is here https://github.com/wemersonjanuario/laravelpdf/pull/9 , hope it gonna be accepted soon.

**Comment by wemersonjanuario** [comment]
merged , thanks for the contribution.

**Comment by dpovshed** [comment]
Thanks for the rapid turnaround!

I would also suggest you release 1.0.3 since my update of the documentation already referring to it (I did it for my fork).

Cheers,
Dennis

**Comment by wemersonjanuario** [comment]
Done!
